package com.truextend.s4.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.HashSet;
import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "courses")
public class Course {
    // I am implying that the code will be generated by the user
    // and it may have alphanumeric characters
    @Id
    @NotNull
    @Column(name = "code")
    private String code;
    @NotNull
    @Column(name = "title")
    private String title;
    @NotNull
    @Column(name = "description")
    private String description;
    @ManyToMany(mappedBy = "courses", fetch = FetchType.EAGER)
    private Set<Student> students = new HashSet<>();

    public Course(String code, String title, String description, Set<Student> students) {
        this.code = code;
        this.title = title;
        this.description = description;
        this.students = students;
    }
}
